### ISSUE TITLE
f8app 2017  error

### ISSUE THREAD

**Issue by hrdzkj** [fbsamples/f8app#215] opened 2018-04-17 08:44 UTC
Local setup is complete and docker is running. Along with it parse server and Mongo. Local Parse dashboard is showing data as well。when the app lunche, this is the error:

ndefined is not a function (evaluating '_reactNative2.default.setAsyncStorage(_reactNative3.AsyncStorage)')
setup
    setup.js:41:2
componentProviderInstrumentationHook
    AppRegistry.js:58:36
run
    AppRegistry.js:105:47
runApplication
    AppRegistry.js:177:26
__callFunction
    MessageQueue.js:250:47
<unknown>
    MessageQueue.js:101:26
__guard
    MessageQueue.js:218:6
callFunctionReturnFlushedQueue
    MessageQueue.js:100:17

**Comment by caabernathy** [comment] 2018-04-18 19:57
This is duplicate of #219, see the solution there.

**Closed by caabernathy** 2018-04-18 19:57 UTC
